version: '3.3'

services:
  db:
    image: postgres
    container_name: postgresdatabase
    restart: always
    environment:
      POSTGRES_DB: expenses
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  
  app:
    build: .
    container_name: app
    ports:
      - '3000:3000'
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - DATABASE_CONECTION_HOST=postgresdatabase
      - DATABASE_CONECTION_USERNAME=
      - DATABASE_CONECTION_PASS=
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  postgres-data: